"""add_full_text_search

Revision ID: 20c7a88eb805
Revises: 446bd372e8a3
Create Date: 2026-01-13 21:23:26.556038

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20c7a88eb805"
down_revision: Union[str, Sequence[str], None] = "446bd372e8a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True))
    op.create_index(
        "ix_messages_search_vector",
        "messages",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # Заполняем существующие данные (UPDATE)
    # Используем coalesce, чтобы склеить русский и английский парсеры
    op.execute("""
        UPDATE messages
        SET search_vector =
            to_tsvector('russian', content) || 
            to_tsvector('english', content)
    """)
    # Создаем функцию триггера
    # Она будет вызываться при каждом INSERT или UPDATE content
    op.execute("""
        CREATE FUNCTION messages_search_trigger() RETURNS trigger AS $$
        begin
          new.search_vector :=
            to_tsvector('russian', new.content) ||
            to_tsvector('english', new.content);
          return new;
        end
        $$ LANGUAGE plpgsql;
    """)
    # Вешаем триггер на таблицу
    op.execute("""
        CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
        ON messages FOR EACH ROW EXECUTE FUNCTION messages_search_trigger();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS tsvectorupdate ON messages")
    op.execute("DROP FUNCTION IF EXISTS messages_search_trigger")
    op.drop_index("ix_messages_search_vector", table_name="messages", postgresql_using="gin")
    op.drop_column("messages", "search_vector")
    # ### end Alembic commands ###
