"""add media fields

Revision ID: 637d6dee3223
Revises: 20c7a88eb805
Create Date: 2026-01-21 08:55:56.636593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637d6dee3223'
down_revision: Union[str, Sequence[str], None] = '20c7a88eb805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('preview_url', sa.String(length=500), nullable=True))
    op.add_column('messages', sa.Column('media_width', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('media_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'media_height')
    op.drop_column('messages', 'media_width')
    op.drop_column('messages', 'preview_url')
    # ### end Alembic commands ###
