"""add invite_token

Revision ID: 6e5d186ab445
Revises: 2806bc89ba00
Create Date: 2026-03-10 17:34:47.106652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5d186ab445'
down_revision: Union[str, Sequence[str], None] = '2806bc89ba00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('invite_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_chats_invite_token'), 'chats', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_invite_token'), table_name='chats')
    op.drop_column('chats', 'invite_token')
    # ### end Alembic commands ###
