"""add_user_online_status

Revision ID: 9f4e4d2df9fa
Revises: 022131bd4110
Create Date: 2025-12-20 16:05:00.133375

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f4e4d2df9fa"
down_revision: Union[str, Sequence[str], None] = "022131bd4110"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_online", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "users",
        sa.Column(
            "last_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_seen")
    op.drop_column("users", "is_online")
    # ### end Alembic commands ###
