"""add media fields2

Revision ID: bdf6683386bb
Revises: 637d6dee3223
Create Date: 2026-01-21 11:15:50.279035

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdf6683386bb"
down_revision: Union[str, Sequence[str], None] = "637d6dee3223"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE messagetype ADD VALUE 'IMAGE'")
        op.execute("ALTER TYPE messagetype ADD VALUE 'VIDEO'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
