"""add_description_to_chats

Revision ID: d0c784d7d18f
Revises: 9f4e4d2df9fa
Create Date: 2025-12-23 15:15:44.796338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c784d7d18f'
down_revision: Union[str, Sequence[str], None] = '9f4e4d2df9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'description')
    # ### end Alembic commands ###
