name: Deploy to Production

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/peddler
            git pull origin main

            # Перезапуск контейнеров с новой сборкой
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up --build -d

            # Очистка старых образов для экономии места на SSD
            docker image prune -af
